version: '3.7'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:9.1.1
    ports:
      - '6900:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana-data:
