server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    url: jdbc:mariadb://db.cholewa.cloud:3306/monitoring
    username: monitoring
    password: monitoring
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
