version: '3.7'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.38.0
    ports:
      - '9090:9090'
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:
